In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
dataset = pd.read_csv('Placement_Data_Full_Class.csv')
dataset.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,CGPA,degree_t,workex,etest_p,specialisation,Masters,status
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
4,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed

In [ ]:
dataset.tail()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,CGPA,degree_t,workex,etest_p,specialisation,Masters,status
210,199,F,67.0,Central,70.0,Central,Commerce,65.0,Others,No,88.00,Mkt&HR,71.96,Not Placed
211,202,M,54.2,Central,63.0,Others,Science,58.0,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed
212,207,M,41.0,Central,42.0,Central,Science,60.0,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed
213,209,F,43.0,Central,60.0,Others,Science,65.0,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   CGPA            215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  Masters         215 non-null    float64
 13  status          215 non-null    object
dtypes: float64(5), int64(1), object(8)
memory usage: 23.6+ KB

In [ ]:
dataset = dataset.drop('sl_no', axis=1);

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          215 non-null    object
 1   ssc_p           215 non-null    float64
 2   ssc_b           215 non-null    object
 3   hsc_p           215 non-null    float64
 4   hsc_b           215 non-null    object
 5   hsc_s           215 non-null    object
 6   CGPA            215 non-null    float64
 7   degree_t        215 non-null    object
 8   workex          215 non-null    object
 9   etest_p         215 non-null    float64
 10  specialisation  215 non-null    object
 11  Masters         215 non-null    float64
 12  status          215 non-null    object
dtypes: float64(5), object(8)
memory usage: 22.0+ KB

In [ ]:
dataset["gender"] = dataset["gender"].astype('category')
dataset["ssc_b"] = dataset["ssc_b"].astype('category')
dataset["hsc_b"] = dataset["hsc_b"].astype('category')
dataset["degree_t"] = dataset["degree_t"].astype('category')
dataset["workex"] = dataset["workex"].astype('category')
dataset["specialisation"] = dataset["specialisation"].astype('category')
dataset["status"] = dataset["status"].astype('category')
dataset["hsc_s"] = dataset["hsc_s"].astype('category')
dataset.dtypes

sl_no                int64
gender            category
ssc_p              float64
ssc_b             category
hsc_p              float64
hsc_b             category
hsc_s             category
CGPA               float64
degree_t          category
workex            category
etest_p            float64
specialisation    category
Masters            float64
status            category
dtype: object

In [ ]:
dataset["gender"]=dataset["gender"].cat.codes
dataset["ssc_b"]=dataset["ssc_b"].cat.codes
dataset["hsc_b"]=dataset["hsc_b"].cat.codes
dataset["degree_t"]=dataset["degree_t"].cat.codes
dataset["workex"]=dataset["workex"].cat.codes
dataset["specialisation"]=dataset["specialisation"].cat.codes
dataset["status"]=dataset["status"].cat.codes
dataset["hsc_s"]=dataset["hsc_s"].cat.codes
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,CGPA,degree_t,workex,etest_p,specialisation,Masters,status
0,1,1,67.00,1,91.00,1,1,58.00,2,0,55.00,1,58.80,1
1,2,1,79.33,0,78.33,1,2,77.48,2,1,86.50,0,66.28,1
2,3,1,65.00,0,68.00,0,0,64.00,0,0,75.00,0,57.80,1
3,5,1,85.80,0,73.60,0,1,73.30,0,0,96.80,0,55.50,1
4,8,1,82.00,0,64.00,0,2,66.00,2,1,67.00,0,62.14,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,199,0,67.00,0,70.00,0,1,65.00,1,0,88.00,1,71.96,0
211,202,1,54.20,0,63.00,1,2,58.00,0,0,79.00,1,58.44,0
212,207,1,41.00,0,42.00,0,2,60.00,0,0,97.00,0,53.39,0
213,209,0,43.00,0,60.00,1,2,65.00,0,0,92.66,1,62.92,0
214,215,1,62.00,0,58.00,1,2,53.00,0,0,89.00,1,60.22,0

In [ ]:
x = dataset.iloc[:,:-1]
x

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,CGPA,degree_t,workex,etest_p,specialisation,Masters
0,1,67.00,1,91.00,1,1,58.00,2,0,55.00,1,58.80
1,1,79.33,0,78.33,1,2,77.48,2,1,86.50,0,66.28
2,1,65.00,0,68.00,0,0,64.00,0,0,75.00,0,57.80
3,1,85.80,0,73.60,0,1,73.30,0,0,96.80,0,55.50
4,1,82.00,0,64.00,0,2,66.00,2,1,67.00,0,62.14
...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,67.00,0,70.00,0,1,65.00,1,0,88.00,1,71.96
211,1,54.20,0,63.00,1,2,58.00,0,0,79.00,1,58.44
212,1,41.00,0,42.00,0,2,60.00,0,0,97.00,0,53.39
213,0,43.00,0,60.00,1,2,65.00,0,0,92.66,1,62.92
214,1,62.00,0,58.00,1,2,53.00,0,0,89.00,1,60.22

In [ ]:
y=dataset.iloc[:,-1]
y

0      1
1      1
2      1
3      1
4      1
      ..
210    0
211    0
212    0
213    0
214    0
Name: status, Length: 215, dtype: int8

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
clf = LogisticRegression()
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
y_pred

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0],
      dtype=int8)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
cf = confusion_matrix(y_test, y_pred)
cf

array([[12,  3],
       [ 1, 27]])

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.9069767441860465